#!/usr/bin/env python3
"""Generate the annotated reasoning-example appendix from REAL judge evidence
quotes, each verified to appear in the raw recorded trace (grounded, never
invented). Emits paper/semantic_examples.tex + paper/semantic_examples.json.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
from common import read_jsonl

sys.path.insert(0, str(ROOT / "analysis"))
from semantic_trace import load_trace

RAW = ROOT / "results/raw"

# mechanism -> (variant that induces it, annotation field)
TARGETS = [
    ("Unused solution branches", "multiple_approaches", "unused_branches",
     "H-S1: branches elaborated then discarded; only one is implemented"),
    ("Redundant verification", "max_certainty", "redundant_verification",
     "H-S3: re-establishing an already-settled fact with no new evidence"),
    ("Post-solution reasoning", "max_certainty", "post_solution_reasoning",
     "H-S3: deliberation after the last edit and a fully-green test"),
    ("Unsupported assumptions", "misleading_architecture", "unsupported_assumptions",
     "H-S4: claims never grounded in inspected code (induced by a wrong hint)"),
    ("Task restatement / elaboration", "deep_thinking", "task_restatements",
     "H-S2 context: repetition inside deep-thinking traces (judge-weak field; shown for illustration, quantified via deterministic proxies)"),
]


def esc(s):
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\^{}")):
        s = s.replace(a, b)
    return s


def norm_ws(s):
    return re.sub(r"\s+", " ", s).strip().lower()


def find_in_trace(run_id, quote):
    """Verify quote appears in the raw recorded trace; return surrounding
    context (up to 320 chars) or None."""
    turns, _ = load_trace(RAW / run_id)
    if turns is None:
        return None
    q = norm_ws(quote)
    for t in turns:
        for src in (t["thinking"], t["text"]):
            if not src:
                continue
            flat = norm_ws(src)
            i = flat.find(q)
            if i >= 0:
                # map back approximately using the raw text
                j = norm_ws(src).find(q)
                # take surrounding window from raw by scanning words
                words = src.split()
                joined = norm_ws(" ".join(words))
                k = joined.find(q)
                if k < 0:
                    return src[:320]
                # char window in raw text around first occurrence of quote's
                # first 5 words
                head = " ".join(quote.split()[:5])
                m = re.search(re.escape(head), src, re.IGNORECASE)
                if m:
                    s = max(0, m.start() - 120)
                    return src[s:m.start() + 240]
                return src[:320]
    return None


def main():
    ann = {}
    ledger = {r["run_id"]: r for r in read_jsonl(ROOT / "results/runs.jsonl")
              if "run_id" in r}
    for j in read_jsonl(ROOT / "results/semantic/annotations_primary.jsonl"):
        if j.get("annotation"):
            ann[j["run_id"]] = j["annotation"]
    tex = [
        "% AUTO-GENERATED by paper/make_semantic_examples.py from judge",
        "% evidence quotes, each verified against the raw recorded trace.",
        r"\section{Annotated Reasoning-Trace Examples}",
        r"\label{app:semantic-examples}",
        r"Each example below is a REAL excerpt from a recorded reasoning",
        r"trace in the corpus, located by the condition-blind judge's",
        r"mandatory evidence quote for the named mechanism and re-verified",
        r"verbatim against the raw trace file. Excerpts are shown with",
        r"minimal surrounding context; run identifiers give model, task,",
        r"and condition. These illustrate what the mechanism counts in",
        r"Section~\ref{sec:semantic} actually refer to.",
    ]
    picked = {}
    out_json = []
    for title, variant, field, note in TARGETS:
        candidates = []
        for rid, a in ann.items():
            r = ledger.get(rid)
            if not r or r["variant"] != variant:
                continue
            for ev in a.get("evidence") or []:
                if ev.get("field", "").endswith(field) and ev.get("quote") \
                        and len(ev["quote"].split()) >= 6:
                    candidates.append((rid, ev))
        found = None
        for rid, ev in candidates:
            ctx = find_in_trace(rid, ev["quote"])
            if ctx:
                found = (rid, ev, ctx)
                break
        if not found:
            print(f"WARNING: no trace-verified example for {field}")
            continue
        rid, ev, ctx = found
        r = ledger[rid]
        picked[field] = rid
        out_json.append({"mechanism": field, "run_id": rid,
                         "quote": ev["quote"], "turn": ev.get("turn"),
                         "verified_in_trace": True})
        tex.append(r"\paragraph{" + esc(title) + r"}")
        tex.append(esc(note) + ".")
        tex.append(f"Run: \\texttt{{{esc(r['model'].split('/')[-1])}}}, task "
                   f"\\texttt{{{esc(r['task_id'])}}}, condition "
                   f"\\texttt{{{esc(variant)}}}, turn {ev.get('turn')}.")
        tex.append(r"\emph{Judge evidence quote (verbatim from the recorded trace):}"
                   + r"\begin{quote}\small\ttfamily " + esc(ev["quote"]) + r"\end{quote}")
        tex.append(r"\emph{Surrounding trace context:}\begin{quote}\scriptsize\ttfamily "
                   + esc(ctx.replace("\n", " ")) + r"...\end{quote}")
    (ROOT / "paper/semantic_examples.tex").write_text("\n".join(tex) + "\n")
    json.dump(out_json, open(ROOT / "paper/semantic_examples.json", "w"), indent=1)
    print(f"OK: {len(out_json)}/{len(TARGETS)} mechanisms illustrated with "
          f"trace-verified quotes")


if __name__ == "__main__":
    main()
